# This workflow will automatically add labels to the PR
name: Labeler
# Trigger the workflow on pull request events
on: [pull_request]
jobs:
  # Action to automatically add labels based on the PR files
  label:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
