# This workflow will set a number or reviewers depending on the tags
name: Label Reviews
# Trigger the workflow on pull requests
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - ready_for_review
  pull_request_review:
    types:
      - submitted
      - edite_d
      - dismissed
jobs:
  require-reviewers:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action@v0.1-alpha2
        with:
          github_token: ${{ secrets.PAT }}
