# This workflow will automatically post comments on PRs that have certain labels
name: Label Commenter
# Trigger the workflow on labels added or removed for PRs
on: [pull_request]
jobs:
  require-reviewers:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action
        with:
          github_token: ${{ secrets.PAT }}
