# This workflow will automatically post comments on PRs that have certain labels
name: Label Commenter
# Trigger the workflow on labels added or removed for PRs
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.PAT }}
